trigger:
- main

pool:
  name: MyLinux
  demands:
    - agent.name -equals myAgent

steps:
- checkout: self

- script: ls -la $(Build.SourcesDirectory)
  displayName: 'Checking file in repos'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the application'

- script: npm test
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathToPublish: 'dist'
    artifactName: 'drop'
    publishLocation: 'Container'
