trigger:
- main

pool:
  name: MyLinux
  demands:
    - agent.name -equals myAgent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x' 
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the application'

- script: npm test
  displayName: 'Run tests'
